//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication {
	
	
	public partial class Editorial {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder head;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton4;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton1;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton2;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton3;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton7;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton6;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton11;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton12;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton8;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton9;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton10;
	}
}
